PewterCity_Mart_Text_BoughtWeirdFishFromShadyGuy::
    .string "A shady old guy sucked me into\n"
    .string "buying this weird fish POKéMON!\p"
    .string "It's totally weak and it cost ¥500!$"

PewterCity_Mart_Text_GoodThingsIfRaiseMonsDiligently::
    .string "Good things can happen if you raise\n"
    .string "POKéMON diligently.\p"
    .string "Even the weak ones can surprise\n"
    .string "you if you don't give up on them.$"

PewterCity_Mart_Text_NotReadyComeBackLater::
    .string "Hi, I'm afraid I'm still getting\n"
    .string "things ready here.\p"
    .string "Would you mind coming back in a bit?$"

