PokemonTower_6F_Text_AngelicaIntro::
    .string "Give…me…\n"
    .string "blood…$"

PokemonTower_6F_Text_AngelicaDefeat::
    .string "Groan!$"

PokemonTower_6F_Text_AngelicaPostBattle::
    .string "I feel anemic and weak…$"

PokemonTower_6F_Text_EmileIntro::
    .string "I'm here to visit my dear departed\n"
    .string "friend, but a battle ought to lift\l"
    .string "my spirits.$"

PokemonTower_6F_Text_EmileDefeat::
    .string "Wonderful!$"

PokemonTower_6F_Text_EmilePostBattle::
    .string "Really we should keep quiet here.\n"
    .string "But I won't tell anyone if you don't.$"

PokemonTower_6F_Text_EmileNotEnoughPokemon::
    .string "I'd happily battle you if you\n"
    .string "would bring another POKéMON."

PokemonTower_6F_Text_JenniferIntro::
    .string "Ke…ke…ke…\n"
    .string "ke…ke…ke!$"

PokemonTower_6F_Text_JenniferDefeat::
    .string "Keee!$"

PokemonTower_6F_Text_JenniferPostBattle::
    .string "What's going on here?$"

PokemonTower_6F_Text_BeGoneIntruders::
    .string "Be gone…\n"
    .string "Intruders…$"

PokemonTower_6F_Text_GhostWasCubonesMother::
    .string "The ghost was the restless spirit\n"
    .string "of CUBONE's mother!$"

PokemonTower_6F_Text_MothersSpiritWasCalmed::
    .string "The mother's spirit was calmed.\p"
    .string "It departed to the afterlife…$"

