CinnabarIsland_Gym_Text_BlaineIntro::
    .string "Hello, who are you?\p"
    .string "Oh? A POKéMON LEAGUE challenger?\p"
    .string "Hah!\p"
    .string "You must be determined, to come\n"
    .string "all the way out here!\p"
    .string "Very well!\p"
    .string "I am BLAINE, the red-hot LEADER\n"
    .string "of CINNABAR GYM!\p"
    .string "My fiery POKéMON are all rough\n"
    .string "and ready with intense heat!\p"
    .string "They incinerate all challengers!\p"
    .string "Hah!\n"
    .string "Let's begin!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

CinnabarIsland_Gym_Text_BlaineDefeat::
    .string "I have burned down to nothing!\n"
    .string "Not even ashes remain!\p"
    .string "You have earned the VOLCANOBADGE.$"

CinnabarIsland_Gym_Text_ExplainOverheat::
    .string "OVERHEAT is the ultimate fire\n"
    .string "technique.\p"
    .string "Don't waste it on WATER POKéMON.$"

CinnabarIsland_Gym_Text_ExplainVolcanoBadge::
    .string "Hah!\p"
    .string "The VOLCANOBADGE heightens the\n"
    .string "SPECIAL stats of your POKéMON.\p"
    .string "Here, you can have this, too!$"

CinnabarIsland_Gym_Text_ReceivedTM50FromBlaine::
    .string "{PLAYER} received TM50\n"
    .string "from BLAINE.$"

CinnabarIsland_Gym_Text_BlainePostBattle::
    .string "TM50 contains OVERHEAT.\n"
    .string "Teach it to FIRE-type POKéMON.\p"
    .string "VULPIX or CHARMELEON would be\n"
    .string "ideal for that move.$"

CinnabarIsland_Gym_Text_MakeSpaceForThis::
    .string "Make space for this, child!$"

CinnabarIsland_Gym_Text_CecilyIntro::
    .string "Check out my cute FIRE-type\n"
    .string "POKéMON!$"

CinnabarIsland_Gym_Text_CecilyDefeat::
    .string "Yow!\n"
    .string "Hot, hot, hot!$"

CinnabarIsland_Gym_Text_CecilyPostBattle::
    .string "I lost, but you must admit...\p"
    .string "HOUNDOOM is adorable, right?$"

CinnabarIsland_Gym_Text_QuinnIntro::
    .string "A FIRE-type POKéMON is a very handy\n"
    .string "partner to have in the wilderness.$"

CinnabarIsland_Gym_Text_QuinnDefeat::
    .string "Ouch!$"

CinnabarIsland_Gym_Text_QuinnPostBattle::
    .string "A FIRE-type POKéMON is a very handy\n"
    .string "partner to have in the wilderness.\p"
    .string "But be careful not to start a\n"
    .string "wildfire!$"

CinnabarIsland_Gym_Text_AveryIntro::
    .string "I've studied POKéMON thoroughly.\n"
    .string "You can't win!$"

CinnabarIsland_Gym_Text_AveryDefeat::
    .string "Waah!\n"
    .string "My studies were insufficient!$"

CinnabarIsland_Gym_Text_AveryPostBattle::
    .string "My theories are too complicated\n"
    .string "for you to understand.$"

CinnabarIsland_Gym_Text_CharlotteIntro::
    .string "I like using FIRE-type POKéMON.\n"
    .string "I just do.$"

CinnabarIsland_Gym_Text_CharlotteDefeat::
    .string "Too hot to handle!$"

CinnabarIsland_Gym_Text_CharlottePostBattle::
    .string "I wish there were a magician POKéMON.\n"
    .string "I'd use that!$"

CinnabarIsland_Gym_Text_DerekIntro::
    .string "I know why BLAINE became a\n"
    .string "TRAINER.$"

CinnabarIsland_Gym_Text_DerekDefeat::
    .string "Ow!$"

CinnabarIsland_Gym_Text_DerekPostBattle::
    .string "Our LEADER, BLAINE, became lost\n"
    .string "in the mountains but good.\p"
    .string "Night fell when a fiery bird\n"
    .string "POKéMON appeared.\p"
    .string "Its light allowed BLAINE to find\n"
    .string "his way down safely.$"

CinnabarIsland_Gym_Text_DustyIntro::
    .string "I've been to many GYMS, but this\n"
    .string "one best suits my style.$"

CinnabarIsland_Gym_Text_DustyDefeat::
    .string "Yowza!\n"
    .string "Too hot!$"

CinnabarIsland_Gym_Text_DustyPostBattle::
    .string "PONYTA, NINETALES…\n"
    .string "Those are popular FIRE POKéMON.$"

CinnabarIsland_Gym_Text_ZacIntro::
    .string "Welcome to the CINNABAR GYM,\n"
    .string "challenger! Entertain me, won't you?$"

CinnabarIsland_Gym_Text_ZacDefeat::
    .string "Oh!\n"
    .string "Snuffed out!$"

CinnabarIsland_Gym_Text_ZacPostBattle::
    .string "If you are unwilling to wait for\n"
    .string "BLAINE's return, seek him on\l"
    .string "ONE ISLAND.\p"
    .string "Best of luck to you!$"

CinnabarIsland_Gym_Text_ZacGiveChoiceSpecs::
    .string "Unfortunately our LEADER, BLAINE,\n"
    .string "isn't here...\p"
    .string "He showed up here one morning with a\n"
    .string "packed suitcase, said he was off to\l"
    .string "ONE ISLAND, and off he went...\p"
    .string "I can see your disappointment.\p"
    .string "I can't give you a VOLCANOBADGE, but\n"
    .string "I can give you this as a consolation\l"
    .string "prize.$"

CinnabarIsland_Gym_Text_ZacExplainChoiceSpecs::
    .string "BLAINE loves all sorts of items\n"
    .string "that have strange effects when held\l"
    .string "by a POKéMON.\p"
    .string "Those CHOICE SPECS are an example.\n"
    .string "They increase SP. ATK., but force\l"
    .string "the bearer to repeat a single move.\p"
    .string "Use them wisely!$"

CinnabarIsland_Gym_Text_GymGuyAdvice::
    .string "Yo!\n"
    .string "Champ in the making!\p"
    .string "The hotheaded BLAINE is a FIRE\n"
    .string "POKéMON pro.\p"
    .string "Douse his spirits with water!\p"
    .string "You'd better take some\n"
    .string "BURN HEALS, too.$"

CinnabarIsland_Gym_Text_GymGuyPostVictory::
    .string "{PLAYER}!\n"
    .string "You beat that firebrand!$"

CinnabarIsland_Gym_Text_GymStatue::
    .string "CINNABAR POKéMON GYM\n"
    .string "LEADER: BLAINE\p"
    .string "WINNING TRAINERS:\n"
    .string "{RIVAL}$"

CinnabarIsland_Gym_Text_GymStatuePlayerWon::
    .string "CINNABAR POKéMON GYM\n"
    .string "LEADER: BLAINE\p"
    .string "WINNING TRAINERS:\n"
    .string "{RIVAL}, {PLAYER}$"

CinnabarIsland_Gym_Text_PokemonQuizRules::
    .string "POKéMON Quiz!\p"
    .string "Get it right, and the door opens to\n"
    .string "the next room.\p"
    .string "Get it wrong, and face a TRAINER!\p"
    .string "If you want to conserve your\n"
    .string "POKéMON for the GYM LEADER…\p"
    .string "Then get it right!\n"
    .string "Here we go!$"

CinnabarIsland_Gym_Text_QuizQuestion1::
    .string "CATERPIE evolves into METAPOD?$"

CinnabarIsland_Gym_Text_QuizQuestion2::
    .string "There are nine certified POKéMON\n"
    .string "LEAGUE BADGES?$"

CinnabarIsland_Gym_Text_QuizQuestion3::
    .string "POLIWAG evolves three times?$"

CinnabarIsland_Gym_Text_QuizQuestion4::
    .string "Are electric moves effective\n"
    .string "against GROUND-type POKéMON?$"

CinnabarIsland_Gym_Text_QuizQuestion5::
    .string "POKéMON of the same kind and level\n"
    .string "are not identical?$"

CinnabarIsland_Gym_Text_QuizQuestion6::
    .string "TM28 contains TOMBSTONY?$"

CinnabarIsland_Gym_Text_CorrectGoOnThrough::
    .string "You're absolutely correct!\p"
    .string "Go on through!$"

CinnabarIsland_Gym_Text_SorryBadCall::
    .string "Sorry!\n"
    .string "Bad call!$"

